export const TransactionTypeEnum = {
   SALE: 'SALE_ORDER',
   PURCHASE: 'PURCHASE_ORDER',
   ADJUSTMENT_SURPLUS: 'ADJUSTMENT_SURPLUS',
   ADJUSTMENT_SHORTAGE: 'ADJUSTMENT_SHORTAGE',
   CREDIT_NOTE: 'CREDIT_NOTE',
   DEBIT_NOTE: 'DEBIT_NOTE',
   TRANSFER_ORIGIN: 'TRANSFER_ORIGIN',
   TRANSFER_DESTINY: 'TRANSFER_DESTINY'
};

const PaymentMethodTypes = {
   cash: 'PAYMENT_METHOD_CASH',
   mercadoPago: 'PAYMENT_METHOD_MERCADO_PAGO',
   creditCard: 'PAYMENT_METHOD_CREDIT_CARD',
   finance: 'PAYMENT_METHOD_FINANCE',
   suscription: 'PAYMENT_METHOD_SUSCRIPTION_MERCADO_PAGO',
}

export { PaymentMethodTypes };