export const OrderType = {
   SALE: 'SALE_ORDER',
   PURCHASE: 'PURCHASE_ORDER',
   ADJUSTMENT_SURPLUS: 'ADJUSTMENT_SURPLUS',
   ADJUSTMENT_SHORTAGE: 'ADJUSTMENT_SHORTAGE',
   CREDIT_NOTE: 'CREDIT_NOTE',
   DEBIT_NOTE: 'DEBIT_NOTE',
   TRANSFER_ORIGIN: 'TRANSFER_ORIGIN',
   TRANSFER_DESTINY: 'TRANSFER_DESTINY'
};